# Generated by Django 5.1.7 on 2025-04-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentabancaria',
            old_name='ibam',
            new_name='iban',
        ),
    ]
