# Generated by Django 5.1.7 on 2025-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='piezas',
            field=models.ManyToManyField(related_name='inventarios', through='tienda.Inventario', to='tienda.pieza'),
        ),
    ]
