# Generated by Django 5.1.7 on 2025-05-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_tienda_piezas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='piezas',
            field=models.ManyToManyField(related_name='tienda_Inventarios', through='tienda.Inventario', to='tienda.pieza'),
        ),
    ]
