# Generated by Django 5.1.7 on 2025-05-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_tienda_piezas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
