# Generated by Django 5.1.7 on 2025-05-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='piezas_pedidas',
            field=models.ManyToManyField(related_name='clientes', through='tienda.Pedido', to='tienda.pieza'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tienda.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tienda.pieza'),
        ),
    ]
