# Generated by Django 5.1.7 on 2025-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_cliente_piezas_pedidas_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.FloatField(default=1.0),
        ),
    ]
