# Generated by Django 5.1.7 on 2025-05-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_inventario_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='Producto_Tienda',
        ),
    ]
