# Generated by Django 5.1.7 on 2025-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_cliente_piezas_pedidas_remove_pedido_pieza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
    ]
