# Generated by Django 5.1.7 on 2025-05-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_pedido_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_tienda',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
