# Generated by Django 5.1.7 on 2025-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_rename_cantidad_producto_tienda_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosTerceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=1.0)),
            ],
        ),
    ]
