# Generated by Django 5.1.7 on 2025-05-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_productosterceros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosTerceros',
        ),
    ]
