# Generated by Django 5.1.9 on 2025-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'cliente'), (3, 'vendedor')], default=2),
        ),
    ]
