# Generated by Django 5.1.9 on 2025-06-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Resuelta')], default='P', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='tienda.cliente')),
                ('lineaPedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='tienda.lineapedido')),
            ],
        ),
    ]
